// Vehicle data with images from WordPress
export const FEATURED_VEHICLES = [
  {
    id: 1,
    name: 'Toyota Hilux',
    make: 'Toyota',
    slug: 'toyota-hilux',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/Nova-Hilux-2021_1-scaled-1.jpg',
    featured: true,
  },
  {
    id: 2,
    name: 'Mahindra Thar',
    make: 'Mahindra',
    slug: 'mahindra-thar',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/mahindra_thar_roxx_2024_5k-3840x2160-1-scaled.jpg',
    featured: true,
  },
  {
    id: 3,
    name: 'Isuzu D-Max',
    make: 'Isuzu',
    slug: 'isuzu-dmax',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/1778470-1920x1300-desktop-hd-isuzu-wallpaper-photo.jpg',
    featured: true,
  },
  {
    id: 4,
    name: 'Maruti Jimny',
    make: 'Maruti',
    slug: 'maruti-jimny',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/suzuki_jimny_2018_08.jpg',
    featured: true,
  },
  {
    id: 5,
    name: 'Jeep Wrangler',
    make: 'Jeep',
    slug: 'jeep-wrangler',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/181709-3000x1688-desktop-hd-jeep-background-photo-scaled.jpg',
    featured: false,
  },
  {
    id: 6,
    name: 'Toyota Fortuner',
    make: 'Toyota',
    slug: 'toyota-fortuner',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/toyota-fortuner-right-front-three-quarter0.jpg',
    featured: false,
  },
];

export const ALL_VEHICLES = [
  ...FEATURED_VEHICLES,
  {
    id: 7,
    name: 'Volkswagen Polo',
    make: 'Volkswagen',
    slug: 'volkswagen-polo',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/VW-Polo-7.jpg',
    featured: false,
  },
  {
    id: 8,
    name: 'Hyundai',
    make: 'Hyundai',
    slug: 'hyundai',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/Hyundai-i20-2-jpeg.jpg',
    featured: false,
  },
  {
    id: 9,
    name: 'KIA',
    make: 'KIA',
    slug: 'kia',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/Carens_1920x1080_3.jpg',
    featured: false,
  },
  {
    id: 10,
    name: 'Ford Endeavour',
    make: 'Ford',
    slug: 'ford-endeavour',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/Untitled-design-2024-01-04T133626.142.png',
    featured: false,
  },
  {
    id: 11,
    name: 'Audi',
    make: 'Audi',
    slug: 'audi',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/A240553_web_2880-scaled.jpg',
    featured: false,
  },
  {
    id: 12,
    name: 'BMW',
    make: 'BMW',
    slug: 'bmw',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/bmw-3-series.jpg',
    featured: false,
  },
  {
    id: 13,
    name: 'Ford Ranger',
    make: 'Ford',
    slug: 'ford-ranger',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/Ford-Ranger.jpg',
    featured: false,
  },
  {
    id: 14,
    name: 'Land Rover Defender',
    make: 'Land Rover',
    slug: 'land-rover-defender',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/land-rover-defender-1333693509.jpg',
    featured: false,
  },
  {
    id: 15,
    name: 'Mercedes Benz',
    make: 'Mercedes',
    slug: 'mercedes-benz',
    image: 'https://img.autobacsindia.com/autobacs/vehicles/Mercedes-Benz-E-Class.jpg',
    featured: false,
  },
];
