import type { Metadata } from "next";
import { DM_Sans, Montserrat } from "next/font/google";
import Script from "next/script";
import { headers } from "next/headers";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { CurrencyProvider } from "@/context/CurrencyContext";
import { RateLimitProvider } from "@/context/RateLimitContext";
import { LogRocketProvider } from "@/providers/LogRocketProvider";
import { PostHogProvider } from "@/providers/PostHogProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import { Toaster } from "react-hot-toast";
import GlobalLoadingBar from "@/components/layout/GlobalLoadingBar";
import ConditionalHeader from "@/components/layout/ConditionalHeader";
import CampaignBanner from "@/components/campaign/CampaignBanner";
import ConditionalPromoBanner from "@/components/layout/ConditionalPromoBanner";
import { getNavCategories } from "@/lib/navCategories";
import { getActivePromoBanner } from "@/lib/promoBanner";
import { RETURN_POLICY_QUESTION, RETURN_POLICY_SUMMARY } from "@/lib/constants";
import ConditionalFooter from "@/components/layout/ConditionalFooter";
import SessionExpiredPrompt from "@/components/layout/SessionExpiredPrompt";
import HelpWidget from "@/components/layout/HelpWidget";
import { SITE_URL } from "@/lib/siteUrl";
import { GOOGLE_ADS_ID, isGoogleAdsEnabled } from "@/lib/googleAds";
import { META_PIXEL_ID, isMetaPixelEnabled } from "@/lib/metaPixel";
import { GTM_ID, GTM_DATA_LAYER, isGtmEnabled } from "@/lib/gtm";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  display: "swap",
});

// ──────────────────────────────────────────────────────────────────────────
// SITE DISPLAY FONT — single source of truth.
// The redesigned UI uses Montserrat everywhere via the `--font-montserrat`
// CSS variable (consumed by `--display-font` in home-redesign.css and any
// future redesigned page). To change the whole site's font, swap this one
// import (e.g. `Inter`, `Poppins`) and its `weight` list — nothing else.
// ──────────────────────────────────────────────────────────────────────────
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "ROAVION - Powered by AutoBacs India",
    template: "%s | Autobacs India"
  },
  description: "Shop premium automotive accessories, body kits, and performance parts from India's trusted auto parts retailer",
  manifest: "/site.webmanifest",
  icons: {
    // Generated by RealFaviconGenerator. These entries render the standard
    // <link rel="icon" …> / apple-touch-icon / shortcut icon tags in <head>.
    icon: [
      { url: "/favicon-96x96.png", type: "image/png", sizes: "96x96" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    shortcut: "/favicon.ico",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  
  // Canonical URL
  alternates: {
    canonical: SITE_URL,
    languages: {
      'en-IN': SITE_URL,
      'en': SITE_URL,
    },
  },
  
  // Open Graph metadata for social sharing
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: "Autobacs India",
    title: "Autobacs India | Premium Automotive Accessories",
    description: "Shop premium automotive accessories, body kits, and performance parts from India's trusted auto parts retailer",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Autobacs India - Premium Automotive Accessories",
      },
    ],
  },
  
  // Twitter Card metadata
  twitter: {
    card: "summary_large_image",
    title: "Autobacs India | Premium Automotive Accessories",
    description: "Shop premium automotive accessories, body kits, and performance parts",
    images: ["/og-image.jpg"],
    creator: "@autobacsindia",
    site: "@autobacsindia",
  },
  
  // Additional metadata
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  // Verification
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
  },
  
  // FAQ Schema for common automotive questions
  other: {
    'application/ld+json': JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      'mainEntity': [
        {
          '@type': 'Question',
          'name': 'What types of automotive accessories do you sell?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'We sell premium automotive accessories including body kits, performance parts, lighting solutions, interior accessories, and vehicle-specific modifications for Indian vehicles.'
          }
        },
        {
          '@type': 'Question',
          'name': 'Do you offer installation services for automotive accessories?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'Yes, we offer professional installation services for most automotive accessories at our authorized service centers across India.'
          }
        },
        {
          '@type': 'Question',
          // Structured data is a machine-readable claim Google may surface directly
          // in results, so it must state the policy the backend actually enforces.
          'name': RETURN_POLICY_QUESTION,
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': RETURN_POLICY_SUMMARY
          }
        },
        {
          '@type': 'Question',
          'name': 'Do you ship automotive accessories across India?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'Yes, we provide nationwide shipping for automotive accessories with free shipping on orders over ₹2,500.'
          }
        },
        {
          '@type': 'Question',
          'name': 'How do I choose the right automotive accessories for my vehicle?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'Our vehicle-specific product mapping ensures compatibility. You can filter products by your vehicle make and model to find perfectly compatible accessories.'
          }
        }
      ]
    })
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the nonce that middleware.ts generated for this request and forwarded
  // via the x-nonce request header. Pass it to <Script> so the Razorpay script
  // is trusted by the nonce-based CSP, and expose it in a <meta> tag so that
  // client-side code (useRazorpay) can read it when creating dynamic scripts.
  const nonce = (await headers()).get('x-nonce') ?? undefined;

  // Resolve the header category nav server-side (data-driven, cached) so it
  // stays in sync with admin-managed categories and renders in the SSR HTML.
  const navCategories = await getNavCategories();

  // Site-wide promo strip (Onam/Diwali/sale). Resolved on the server so it lands
  // in the initial HTML with its space already reserved; returns null whenever no
  // campaign is scheduled, which is the normal state for most of the year.
  const promoBanner = await getActivePromoBanner();

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {nonce && <meta name="csp-nonce" content={nonce} />}
        {/* Warm the TLS connection to the image origin — it serves the eager
            mobile hero LCP image and every product image, so this speeds the
            first image on any page.

            R2 is FIRST because it is now the origin for essentially everything:
            the catalog, articles, banners and the brand lockup all moved there.
            Preconnecting to Cloudinary alone (as this did) spent the handshake
            on a host the page no longer requests.

            Cloudinary is kept as a second hint until decommission: a handful of
            assets still point at it — 16 unpublished products and 6 historical
            order snapshots — and an unused preconnect costs one idle socket,
            while a missing one costs a full handshake on the LCP image. */}
        <link rel="preconnect" href="https://img.autobacsindia.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://res.cloudinary.com" crossOrigin="anonymous" />

        {/* ── Third-party tags: raw <script>, deliberately NOT next/script ─────
            next/script emits EVERY strategy — including beforeInteractive — as a
            JSON string inside `(self.__next_s=…).push([…])`, which the Next
            runtime replays once the client bundle boots. In the App Router
            "beforeInteractive" means before HYDRATION, not "in the HTML head".
            Measured on prod 2026-09-04, that had two costs:

              1. The served HTML contained NO Google tag at all — only the
                 <noscript> iframe below was real markup. Google's tag-coverage
                 report therefore listed live, correctly-firing pages as
                 "untagged", and so would any other install checker.
              2. A visitor who left before the bundle executed was never counted,
                 so Ads silently under-reported the fastest bounces.

            Raw <script> tags run during HTML parse, which fixes both. They cost
            no render-blocking time: each inline snippet is a few hundred bytes
            and every library they pull (gtm.js, gtag.js, fbevents.js) is async.

            ⚠ Do NOT "modernise" these back to <Script> — that is the regression.
            next/script stays in use further down for Razorpay, which genuinely
            wants lazy loading and is not subject to any coverage report.

            nonce={nonce} is REQUIRED on every one — the strict nonce CSP
            (lib/csp.ts) blocks any unnonce'd script; 'strict-dynamic' then
            propagates trust to whatever they inject. Every value interpolated
            below is shape-validated by its isXEnabled guard (GTM-…, AW-digits,
            digits) so none of them can break out of the snippet.

            ORDER MATTERS: each queue must be created before the loader that
            drains it. Keep every queue init immediately above its loader. */}

        {/* Google Tag Manager. Rendered only when a real container id is set
            (isGtmEnabled), so Preview/local builds never load a container whose
            tags would fire into live datasets.

            GTM does NOT own conversion tracking here: the Google Ads tag below
            and the Meta Pixel are loaded directly and fire their own events. A
            duplicate conversion tag built inside the GTM UI would count every
            order twice — see lib/gtm.ts. */}
        {isGtmEnabled && (
          <>
            {/* GTM's queue must exist before anything pushes to it: page-mount
                effects fire the moment a route hydrates, and a push against an
                undefined array throws inside the effect. The array is a queue —
                GTM drains whatever accumulated before gtm.js landed, so nothing
                is lost by the container itself arriving later.

                Note the name: `gtmDataLayer`, NOT the default `dataLayer`. See
                lib/gtm.ts — sharing one array let GTM replay gtag's `config`
                and triple the page_view beacons. */}
            <script
              nonce={nonce}
              dangerouslySetInnerHTML={{
                __html: `window.${GTM_DATA_LAYER} = window.${GTM_DATA_LAYER} || [];`,
              }}
            />
            {/* Google's stock snippet, plus the `j.setAttribute('nonce', …)`
                line Google documents for nonce-based CSPs. Without it the
                injected gtm.js carries no nonce and survives only on
                'strict-dynamic' — which Chrome honours, but it leaves GTM with
                no nonce to copy onto the tags IT injects. Any Custom HTML tag
                added in the GTM UI later would then be blocked on a browser
                without 'strict-dynamic' support, and blocked inline script
                fails silently. The nonce is already public in the page source,
                so interpolating it here reveals nothing. */}
            <script
              nonce={nonce}
              dangerouslySetInnerHTML={{
                __html: `(function(w,d,s,l,i,n){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;if(n)j.setAttribute('nonce',n);
f.parentNode.insertBefore(j,f);
})(window,document,'script','${GTM_DATA_LAYER}','${GTM_ID}',${JSON.stringify(nonce ?? '')});`,
              }}
            />
          </>
        )}

        {/* Google Tag (gtag.js) for Google Ads conversion tracking.
            Rendered only when a real AW- id is configured (isGoogleAdsEnabled),
            so unset/preview environments never load a broken tag or fire real
            conversions. The conversion event itself fires from
            app/order/[orderId]/success (PurchaseTracker). */}
        {isGoogleAdsEnabled && (
          <>
            {/* The stub + config MUST exist before any app code calls gtag().
                Page-mount effects fire events the moment a route hydrates
                (products/[slug] sends view_item from SSR'd data); when the stub
                did not exist yet at that point, every such event was dropped
                SILENTLY. Events that happen a beat later (begin_checkout, which
                waits on the cart fetch) got through — which is exactly the
                half-working funnel we once saw in Google Ads.

                The library itself stays async: the stub queues commands into
                window.dataLayer and gtag.js drains that queue in order when it
                lands, so nothing is lost — and 'config' is always queued ahead
                of any event. */}
            <script
              nonce={nonce}
              dangerouslySetInnerHTML={{
                __html: `window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
window.gtag = gtag;
gtag('js', new Date());
gtag('config', '${GOOGLE_ADS_ID}');`,
              }}
            />
            <script
              async
              src={`https://www.googletagmanager.com/gtag/js?id=${GOOGLE_ADS_ID}`}
              nonce={nonce}
            />
          </>
        )}

        {/* Meta Pixel base. Rendered only when a real numeric pixel id is set
            (isMetaPixelEnabled), so unset/preview builds never load it or fire
            events into the live dataset. 'strict-dynamic' trusts the fbevents.js
            the snippet injects. Fires PageView here; ViewContent/AddToCart/
            Purchase fire from their pages via lib/metaPixel.ts (Purchase is
            deduped with server CAPI). Meta's own "pixel not detected" diagnostic
            reads the served HTML too, which is the other half of why this is a
            raw <script>. */}
        {isMetaPixelEnabled && (
          <script
            nonce={nonce}
            dangerouslySetInnerHTML={{
              __html: `!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '${META_PIXEL_ID}');
fbq('track', 'PageView');`,
            }}
          />
        )}
      </head>
      <body
        className={`${dmSans.variable} ${montserrat.variable} antialiased`}
      >
        {isGtmEnabled && (
          /* Google Tag Manager (noscript) — the JS-less fallback, which is why
             it carries no nonce: it is markup, not script. Needs
             www.googletagmanager.com in the CSP frame-src (middleware.ts) or the
             browser blocks the iframe. React cannot render an <iframe> as a
             child of <noscript> (it would be parsed as real DOM on the client),
             so the markup is set as raw HTML. */
          <noscript
            dangerouslySetInnerHTML={{
              __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=${GTM_ID}" height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
            }}
          />
        )}
        <LogRocketProvider>
          <PostHogProvider>
          <QueryProvider>
          <AuthProvider>
            <CartProvider>
              <WishlistProvider>
                <RateLimitProvider>
                  <CurrencyProvider>
                      <GlobalLoadingBar />
                      <ConditionalHeader navCategories={navCategories} />
                      {/* Admin-managed occasion strip. Sits directly under the nav
                          on every storefront route except `/`, which mounts it
                          itself below the hero (its nav is fixed and ships inside
                          HomeRedesign). Null when nothing is scheduled. */}
                      <ConditionalPromoBanner banner={promoBanner} />
                      {/* Renders only for a signed-in, eligible campaign customer;
                          returns null the rest of the time (and all year when no
                          campaign is running). */}
                      <CampaignBanner />
                      <main className="flex-1 flex flex-col min-h-screen">{children}</main>
                      <ConditionalFooter />
                      <SessionExpiredPrompt />
                      <HelpWidget />
                      <Toaster
                        position="top-right"
                        toastOptions={{
                          style: {
                            background: "#181a1a",
                            color: "#f0ede7",
                            border: "1px solid #252525",
                            fontFamily: "var(--font-montserrat), system-ui, sans-serif",
                            fontSize: "0.875rem",
                            fontWeight: 500,
                            borderRadius: "0.5rem",
                            boxShadow: "0 8px 24px rgba(0,0,0,0.5)",
                          },
                          success: {
                            iconTheme: { primary: "#c9a870", secondary: "#181a1a" },
                          },
                          error: {
                            iconTheme: { primary: "#dc2626", secondary: "#f0ede7" },
                          },
                        }}
                      />
                      <Script
                        id="razorpay-checkout"
                        src="https://checkout.razorpay.com/v1/checkout.js"
                        strategy="lazyOnload"
                        nonce={nonce}
                      />
                  </CurrencyProvider>
                </RateLimitProvider>
              </WishlistProvider>
            </CartProvider>
          </AuthProvider>
          </QueryProvider>
          </PostHogProvider>
        </LogRocketProvider>
      </body>
    </html>
  );
}
