import type { Metadata } from "next";
import { DM_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { CurrencyProvider } from "@/context/CurrencyContext";
import { RateLimitProvider } from "@/context/RateLimitContext";
import { LogRocketProvider } from "@/providers/LogRocketProvider";
import { PostHogProvider } from "@/providers/PostHogProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import { Toaster } from "react-hot-toast";
import GlobalLoadingBar from "@/components/layout/GlobalLoadingBar";
import ConditionalHeader from "@/components/layout/ConditionalHeader";
import CampaignBanner from "@/components/campaign/CampaignBanner";
import ConditionalPromoBanner from "@/components/layout/ConditionalPromoBanner";
import { getNavCategories } from "@/lib/navCategories";
import { getActivePromoBanner } from "@/lib/promoBanner";
import { RETURN_POLICY_QUESTION, RETURN_POLICY_SUMMARY } from "@/lib/constants";
import ConditionalFooter from "@/components/layout/ConditionalFooter";
import SessionExpiredPrompt from "@/components/layout/SessionExpiredPrompt";
import HelpWidget from "@/components/layout/HelpWidget";
import { SITE_URL } from "@/lib/siteUrl";
import { isGoogleAdsEnabled } from "@/lib/googleAds";
import { isMetaPixelEnabled } from "@/lib/metaPixel";
import { GTM_ID, isGtmEnabled } from "@/lib/gtm";
import {
  gtmQueueSnippet,
  gtmLoaderSnippet,
  googleAdsSnippet,
  metaPixelSnippet,
} from "@/lib/analyticsSnippets";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  display: "swap",
});

// ──────────────────────────────────────────────────────────────────────────
// SITE DISPLAY FONT — single source of truth.
// The redesigned UI uses Montserrat everywhere via the `--font-montserrat`
// CSS variable (consumed by `--display-font` in home-redesign.css and any
// future redesigned page). To change the whole site's font, swap this one
// import (e.g. `Inter`, `Poppins`) and its `weight` list — nothing else.
// ──────────────────────────────────────────────────────────────────────────
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "ROAVION - Powered by AutoBacs India",
    template: "%s | Autobacs India"
  },
  description: "Shop premium automotive accessories, body kits, and performance parts from India's trusted auto parts retailer",
  manifest: "/site.webmanifest",
  icons: {
    // Generated by RealFaviconGenerator. These entries render the standard
    // <link rel="icon" …> / apple-touch-icon / shortcut icon tags in <head>.
    icon: [
      { url: "/favicon-96x96.png", type: "image/png", sizes: "96x96" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    shortcut: "/favicon.ico",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  
  // Canonical URL
  alternates: {
    canonical: SITE_URL,
    languages: {
      'en-IN': SITE_URL,
      'en': SITE_URL,
    },
  },
  
  // Open Graph metadata for social sharing
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: "Autobacs India",
    title: "Autobacs India | Premium Automotive Accessories",
    description: "Shop premium automotive accessories, body kits, and performance parts from India's trusted auto parts retailer",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Autobacs India - Premium Automotive Accessories",
      },
    ],
  },
  
  // Twitter Card metadata
  twitter: {
    card: "summary_large_image",
    title: "Autobacs India | Premium Automotive Accessories",
    description: "Shop premium automotive accessories, body kits, and performance parts",
    images: ["/og-image.jpg"],
    creator: "@autobacsindia",
    site: "@autobacsindia",
  },
  
  // Additional metadata
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  // Verification
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || '',
  },
  
  // FAQ Schema for common automotive questions
  other: {
    'application/ld+json': JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      'mainEntity': [
        {
          '@type': 'Question',
          'name': 'What types of automotive accessories do you sell?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'We sell premium automotive accessories including body kits, performance parts, lighting solutions, interior accessories, and vehicle-specific modifications for Indian vehicles.'
          }
        },
        {
          '@type': 'Question',
          'name': 'Do you offer installation services for automotive accessories?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'Yes, we offer professional installation services for most automotive accessories at our authorized service centers across India.'
          }
        },
        {
          '@type': 'Question',
          // Structured data is a machine-readable claim Google may surface directly
          // in results, so it must state the policy the backend actually enforces.
          'name': RETURN_POLICY_QUESTION,
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': RETURN_POLICY_SUMMARY
          }
        },
        {
          '@type': 'Question',
          'name': 'Do you ship automotive accessories across India?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'Yes, we provide nationwide shipping for automotive accessories with free shipping on orders over ₹2,500.'
          }
        },
        {
          '@type': 'Question',
          'name': 'How do I choose the right automotive accessories for my vehicle?',
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': 'Our vehicle-specific product mapping ensures compatibility. You can filter products by your vehicle make and model to find perfectly compatible accessories.'
          }
        }
      ]
    })
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // NO nonce here, deliberately, and this is the load-bearing decision of the
  // whole ISR change: `headers()` is a Dynamic API, and calling it in the ROOT
  // layout opts EVERY route in the app out of static rendering. That single
  // line was why 0 of ~110 routes were prerendered and every page carried
  // `private, no-store`.
  //
  // The inline analytics scripts below are instead allowed by SHA-256 hash on
  // the strict routes (lib/csp.ts buildStrictCsp) and by 'unsafe-inline' on the
  // public ones. app/checkout/layout.tsx still reads x-nonce for Razorpay —
  // a NESTED layout may, because /checkout is dynamic anyway, and Next still
  // nonces its own scripts there (verified on a production build).

  // Resolve the header category nav server-side (data-driven, cached) so it
  // stays in sync with admin-managed categories and renders in the SSR HTML.
  const navCategories = await getNavCategories();

  // Site-wide promo strip (Onam/Diwali/sale). Resolved on the server so it lands
  // in the initial HTML with its space already reserved; returns null whenever no
  // campaign is scheduled, which is the normal state for most of the year.
  const promoBanner = await getActivePromoBanner();

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* The <meta name="csp-nonce"> tag is gone with the nonce. hooks/useRazorpay.ts
            reads it to stamp the script it injects, and already handles absence
            (`if (nonce) script.nonce = nonce`). On /checkout and /orders/[id] —
            the only places it runs — the strict CSP applies and 'strict-dynamic'
            extends trust from the nonce'd Next bundle that calls it, so the
            injected Razorpay script is allowed with or without the attribute. */}
        {/* Warm the TLS connection to the image origin — it serves the eager
            mobile hero LCP image and every product image, so this speeds the
            first image on any page.

            R2 is FIRST because it is now the origin for essentially everything:
            the catalog, articles, banners and the brand lockup all moved there.
            Preconnecting to Cloudinary alone (as this did) spent the handshake
            on a host the page no longer requests.

            Cloudinary is kept as a second hint until decommission: a handful of
            assets still point at it — 16 unpublished products and 6 historical
            order snapshots — and an unused preconnect costs one idle socket,
            while a missing one costs a full handshake on the LCP image. */}
        <link rel="preconnect" href="https://img.autobacsindia.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://res.cloudinary.com" crossOrigin="anonymous" />

        {/* ── Third-party tags: raw <script>, deliberately NOT next/script ─────
            next/script emits EVERY strategy — including beforeInteractive — as a
            JSON string inside `(self.__next_s=…).push([…])`, which the Next
            runtime replays once the client bundle boots. In the App Router
            "beforeInteractive" means before HYDRATION, not "in the HTML head".
            Measured on prod 2026-09-04, that had two costs:

              1. The served HTML contained NO Google tag at all — only the
                 <noscript> iframe below was real markup. Google's tag-coverage
                 report therefore listed live, correctly-firing pages as
                 "untagged", and so would any other install checker.
              2. A visitor who left before the bundle executed was never counted,
                 so Ads silently under-reported the fastest bounces.

            Raw <script> tags run during HTML parse, which fixes both. They cost
            no render-blocking time: each inline snippet is a few hundred bytes
            and every library they pull (gtm.js, gtag.js, fbevents.js) is async.

            ⚠ Do NOT "modernise" these back to <Script> — that is the regression.
            next/script is still the right tool for Razorpay, which genuinely
            wants lazy loading and is not subject to any coverage report — it
            just no longer belongs in THIS layout. See app/checkout/layout.tsx.

            The bodies live in lib/analyticsSnippets.ts, NOT inline here, and
            that indirection is load-bearing: these scripts carry no nonce (the
            root layout cannot mint one without making every route dynamic), so
            the strict CSP allows them by SHA-256 HASH. A hash matches the body
            byte for byte, so the string that is hashed and the string that is
            rendered must be the SAME string. Editing a snippet here instead of
            there would silently stop it executing on /checkout and friends.
            Every interpolated value is shape-validated by its isXEnabled guard
            (GTM-…, AW-digits, digits) so none can break out of the snippet.

            ORDER MATTERS: each queue must be created before the loader that
            drains it. Keep every queue init immediately above its loader. */}

        {/* Google Tag Manager. Rendered only when a real container id is set
            (isGtmEnabled), so Preview/local builds never load a container whose
            tags would fire into live datasets.

            GTM does NOT own conversion tracking here: the Google Ads tag below
            and the Meta Pixel are loaded directly and fire their own events. A
            duplicate conversion tag built inside the GTM UI would count every
            order twice — see lib/gtm.ts. */}
        {isGtmEnabled && (
          <>
            {/* GTM's queue must exist before anything pushes to it: page-mount
                effects fire the moment a route hydrates, and a push against an
                undefined array throws inside the effect. The array is a queue —
                GTM drains whatever accumulated before gtm.js landed, so nothing
                is lost by the container itself arriving later.

                Note the name: `gtmDataLayer`, NOT the default `dataLayer`. See
                lib/gtm.ts — sharing one array let GTM replay gtag's `config`
                and triple the page_view beacons. */}
            <script dangerouslySetInnerHTML={{ __html: gtmQueueSnippet }} />
            {/* Google's stock loader. The `j.setAttribute('nonce', …)` line it
                used to carry is gone — a hash-allowed script has no nonce to
                propagate. 'strict-dynamic' still extends trust from this script
                to the gtm.js it injects and onward to GTM's own tags, which is
                precisely what strict-dynamic is for. The residual cost is
                browsers that ignore strict-dynamic, where a Custom HTML tag
                added in the GTM UI would be blocked; the script-src host
                allowlist still covers gtm.js itself there. */}
            <script dangerouslySetInnerHTML={{ __html: gtmLoaderSnippet }} />
          </>
        )}

        {/* Google Tag (gtag.js) for Google Ads conversion tracking.
            Rendered only when a real AW- id is configured (isGoogleAdsEnabled),
            so unset/preview environments never load a broken tag or fire real
            conversions. The conversion event itself fires from
            app/order/[orderId]/success (PurchaseTracker). */}
        {isGoogleAdsEnabled && (
          <>
            {/* The stub + config MUST exist before any app code calls gtag().
                Page-mount effects fire events the moment a route hydrates
                (products/[slug] sends view_item from SSR'd data); when the stub
                did not exist yet at that point, every such event was dropped
                SILENTLY. Events that happen a beat later (begin_checkout, which
                waits on the cart fetch) got through — which is exactly the
                half-working funnel we once saw in Google Ads.

                The library itself stays async: the stub queues commands into
                window.dataLayer and gtag.js drains that queue in order when it
                lands, so nothing is lost — and 'config' is always queued ahead
                of any event. */}
            {/* One script, not two: the gtag.js loader is inside this snippet.
                A sibling <script async src> would carry neither nonce nor hash,
                and 'strict-dynamic' ignores host allowlists — so it was blocked
                on every strict route. See lib/analyticsSnippets.ts. */}
            <script dangerouslySetInnerHTML={{ __html: googleAdsSnippet }} />
          </>
        )}

        {/* Meta Pixel base. Rendered only when a real numeric pixel id is set
            (isMetaPixelEnabled), so unset/preview builds never load it or fire
            events into the live dataset. 'strict-dynamic' trusts the fbevents.js
            the snippet injects. Fires PageView here; ViewContent/AddToCart/
            Purchase fire from their pages via lib/metaPixel.ts (Purchase is
            deduped with server CAPI). Meta's own "pixel not detected" diagnostic
            reads the served HTML too, which is the other half of why this is a
            raw <script>. */}
        {isMetaPixelEnabled && (
          <script dangerouslySetInnerHTML={{ __html: metaPixelSnippet }} />
        )}
      </head>
      <body
        className={`${dmSans.variable} ${montserrat.variable} antialiased`}
      >
        {isGtmEnabled && (
          /* Google Tag Manager (noscript) — the JS-less fallback, which is why
             it carries no nonce: it is markup, not script. Needs
             www.googletagmanager.com in the CSP frame-src (middleware.ts) or the
             browser blocks the iframe. React cannot render an <iframe> as a
             child of <noscript> (it would be parsed as real DOM on the client),
             so the markup is set as raw HTML. */
          <noscript
            /*
              Defensive, NOT a proven fix for any specific error.

              With JavaScript enabled the browser parses <noscript> content as
              raw TEXT rather than DOM, so React can never compare it equal to
              what it rendered on the server. Suppressing is the correct posture
              for content that is deliberately un-hydratable: there is no
              client-side behaviour here to preserve.

              ⚠ An earlier version of this comment claimed this caused the React
              #418 on the home page. That was WRONG and is recorded here so it
              is not re-derived: an A/B of two production builds differing only
              in this prop showed #418 in NEITHER. The real #418 is home-page
              only (/privacy, /products, /categories are clean), is a MARKUP
              mismatch (React's `args[]=HTML` means "not text" — it is unrelated
              to dangerouslySetInnerHTML), and does not reproduce on a local
              build, because production's HTML was generated from different
              build-time data. Diagnose it with a dev-mode render of the real
              page, which prints the offending element.
            */
            suppressHydrationWarning
            dangerouslySetInnerHTML={{
              __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=${GTM_ID}" height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
            }}
          />
        )}
        <LogRocketProvider>
          <PostHogProvider>
          <QueryProvider>
          <AuthProvider>
            <CartProvider>
              <WishlistProvider>
                <RateLimitProvider>
                  <CurrencyProvider>
                      <GlobalLoadingBar />
                      <ConditionalHeader navCategories={navCategories} />
                      {/* Admin-managed occasion strip. Sits directly under the nav
                          on every storefront route except `/`, which mounts it
                          itself below the hero (its nav is fixed and ships inside
                          HomeRedesign). Null when nothing is scheduled. */}
                      <ConditionalPromoBanner banner={promoBanner} />
                      {/* Renders only for a signed-in, eligible campaign customer;
                          returns null the rest of the time (and all year when no
                          campaign is running). */}
                      <CampaignBanner />
                      <main className="flex-1 flex flex-col min-h-screen">{children}</main>
                      <ConditionalFooter />
                      <SessionExpiredPrompt />
                      <HelpWidget />
                      <Toaster
                        position="top-right"
                        toastOptions={{
                          style: {
                            background: "#181a1a",
                            color: "#f0ede7",
                            border: "1px solid #252525",
                            fontFamily: "var(--font-montserrat), system-ui, sans-serif",
                            fontSize: "0.875rem",
                            fontWeight: 500,
                            borderRadius: "0.5rem",
                            boxShadow: "0 8px 24px rgba(0,0,0,0.5)",
                          },
                          success: {
                            iconTheme: { primary: "#c9a870", secondary: "#181a1a" },
                          },
                          error: {
                            iconTheme: { primary: "#dc2626", secondary: "#f0ede7" },
                          },
                        }}
                      />
                      {/*
                        Razorpay's checkout script used to be mounted here, on
                        EVERY route. Measured on the live home page that was 175
                        requests / 1.36 MB for a page where nobody can pay. It
                        now lives in app/checkout/layout.tsx (pre-warmed on the
                        money path), and hooks/useRazorpay.ts loads it on demand
                        — idempotently, reading the nonce from the <meta> tag
                        above — anywhere else that can take a payment, such as
                        the retry-payment path on /orders/[id].
                      */}
                  </CurrencyProvider>
                </RateLimitProvider>
              </WishlistProvider>
            </CartProvider>
          </AuthProvider>
          </QueryProvider>
          </PostHogProvider>
        </LogRocketProvider>
      </body>
    </html>
  );
}
